apiVersion: v1
kind: Namespace
metadata:
  name: policies
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: policies
  namespace: policies
spec:
  type: Git
  pathname: https://github.com/radikaled/policy-collection
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: testing
    apps.open-cluster-management.io/git-path: my-policies/policy-sets
    apps.open-cluster-management.io/reconcile-option: replace
  name: policies-subscription
  namespace: policies
spec:
  channel: policies/policies
  placement:
    placementRef:
      kind: PlacementRule
      name: policies-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: policies-placement
  namespace: policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - "true"
